// Design slot → photo. The design handoff names its assets (`hero-service.jpg`,
// `svc-weddings.jpg`, …); the client's originals are camera filenames. This is
// the one place that joins the two.
//
// To swap a photo, change the filename here — nothing else references the
// originals. Names on the right are files in src/assets/images/ (generated by
// `npm run images`), without their extension.

import type { ImageMetadata } from 'astro';

const files = import.meta.glob<{ default: ImageMetadata }>(
  '../assets/images/*.{jpg,png}',
  { eager: true },
);

const SLOTS: Record<string, string> = {
  // --- People (confirmed) ---
  'jan-whites': 'janattherestaurant',              // whites, outside Jan's on the Beach
  'jan-plating': '568101',                         // at the pass, working
  'jan-halibut': 'img-e3144',                      // portrait, Jan's on the Beach whites
  'janet-bw': 'janet-blackwhite-1024x1024',        // the B&W portrait
  'jan-award': 'janwithbiaaward',

  // --- Dishes (confirmed by filename) ---
  'gal-lamb': 'lamchops',
  'gal-turkey': 'turkeydinner',
  'gal-pate': 'chocolate-pate',
  'gal-benny': 'eggs-benny',
  'gal-torte': 'cheesecake',
  'gal-salmon': 'salmononseafoodrisotto',
  'menu-burrowing-owl': 'burrowinowlwinedinner22sept2022',
  // Cropped from screenshot-2026-08-14-204208 — that frame has the video
  // player's Save/share overlay burnt into the top right corner.
  'hero-reviews': '750-2757-edit',                 // hands finishing stuffed poblanos
  'plating': 'screenshot-2026-08-14-203255',       // scallops — chosen by Jan

  // --- Dishes and rooms (from the camera-roll pool, confirmed by Jan) ---
  'hero-service': 'catering',
  'private-dining-tacos': 'tuscan-chicken',
  'svc-weddings': 'chocolate-pate',              // was the clam platter, now on gluten-free
  'svc-corporate': 'screenshot-2026-08-14-210100',  // the buffet line
  'svc-celebrations': 'img-4948',                // chicken on arugula, orchid garnish
  'svc-gluten-free': 'seafood',                  // clams — came down from weddings
  'svc-private': 'img-5843',
  'svc-wine': 'img-5126',
  'gal-shrimp': 'img-4684',
  'gal-grazing': 'img-2401',
  'gal-salad': 'img-4954',
  'gal-crostini': 'img-3199',
  'gal-clams': 'img-5847',
  'gal-braised': 'img-7283',
  'gal-pasta': 'img-4740',
  'gal-soup': 'img-5603',
  'gal-tacos': 'img-1479-edit',

  // --- Photos inside the service pages' narrative sections ---
  'sec-private': 'img-7212',                     // scallop amuse spoons
  // Not the scallop plate — that is already the homepage's `plating`.
  'sec-weddings': 'img-4612',                    // the seafood platter
  'sec-corporate': 'camerazoom-20131116140336064',  // crudite and cheese platters
  'sec-celebrations': 'img-8062',                // a party cocktail
  'sec-gluten-free': 'dsc-0293-01',              // caprese
};

/** Look up a design slot. Throws at build time on a typo rather than
 *  rendering a broken image. */
export function img(slot: string): ImageMetadata {
  const name = SLOTS[slot];
  if (!name) throw new Error(`Unknown image slot "${slot}" — add it to src/data/images.ts`);

  const key = Object.keys(files).find((p) => p.match(/([^/]+)\.(jpg|png)$/)?.[1] === name);
  if (!key) throw new Error(`Slot "${slot}" points at "${name}", which is not in src/assets/images/`);

  return files[key].default;
}
